config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'photos', to: 'photos#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    # authenticated :user do
    #  root :to => 'my_threads#index', as: :authenticated_root
    # end
    # unauthenticated :user do
    root to: 'users/sessions#new', as: :unauthenticated_root
    # end
    # post '/users/sign_up', to: 'users/registrations#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_threads do
    resources :comments
  end
end

# devise_for :users, :controllers => {
#:registrations => 'users/registrations',
#:sessions => 'users/sessions',
#:passwords => "users/passwords"
# }

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :text, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.where(my_thread_id: @my_thread.id).order(created_at: 'desc')
    @myid = session[:user_id]
  end

  def new
    @comment = Comment.new
  end

  def create
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.new(comment_params)
    @comment[:my_thread_id] = @my_thread.id
    @comment[:user_id] = session[:user_id]

    if @comment.save
      redirect_to my_thread_comments_path
    else
      render 'new'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to my_thread_comments_path
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to my_thread_comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :my_thread_id, :user_id)
  end
end

app/helpers/my_threads/comments_helper.rb
# frozen_string_literal: true

module MyThreads::CommentsHelper
end

app/views/comments/edit.html.erb
<h2>コメントを編集</h2>
<%= form_for @comment, :url => {:action => 'update'}  do |f| %>

  <p>
    <%= f.text_area :text, placeholder:'enter text' %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% @comment.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
  <% end %>

<% end %>

app/views/comments/index.html.erb
<h2>スレッド詳細</h2>
<span>自分のID: <%= @myid %></span>
<p><%= simple_format @my_thread.text %></p>

<%= link_to 'コメント作成',new_my_thread_comment_path, class:'header-menu'%>

<% if @my_thread.comments.any? %>
	<ul>
		<% @comment.each do |comment| %>
		<li>
			<%= comment.text %>

			<span>投稿者ID: <%= comment.user_id %></span>

			<% if comment.user_id == @myid %>

				<%= link_to '[編集]',edit_my_thread_comment_path(id: @comment.ids), class:'command' %>

            	<%= link_to '[削除]',my_thread_comment_path(id: @comment.ids), 
            	method: :delete,
            	class:'command',
            	data:{confirm: 'Sure?'}
            	%>
			<% end %>

		</li>
	<% end %>	
	</ul>
<% end %>

app/views/comments/new.html.erb
<h2>コメントを追加</h2>
<%= form_for @comment, :url => {:action => 'create'}  do |f| %>

  <p>
    <%= f.text_area :text, placeholder:'enter text' %>
  </p>

  <p>
    <%= f.submit %>
  </p>
	
  <% @comment.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
  <% end %>

<% end %>