config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'photos', to: 'photos#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    # authenticated :user do
    #  root :to => 'my_threads#index', as: :authenticated_root
    # end
    # unauthenticated :user do
    root to: 'users/sessions#new', as: :unauthenticated_root
    # end
    # post '/users/sign_up', to: 'users/registrations#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_threads do
    resources :comments
  end
end

# devise_for :users, :controllers => {
#:registrations => 'users/registrations',
#:sessions => 'users/sessions',
#:passwords => "users/passwords"
# }

app/models/my_thread.rb
# frozen_string_literal: true

class MyThread < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/my_threads_controller.rb
# frozen_string_literal: true

class MyThreadsController < ApplicationController
  before_action :login_check, only: [:index]

  def index
    @my_threads = MyThread.all.order(created_at: 'desc')
    @myid = session[:user_id]
  end

  def new
    @my_thread = MyThread.new
  end

  def create
    @my_thread = MyThread.new(my_thread_params)
    @my_thread[:user_id] = session[:user_id]
    if @my_thread.save
      redirect_to my_threads_path
    else
      render 'new'

    end
  end

  def edit
    @my_thread = MyThread.find(params[:id])
  end

  def update
    @my_thread = MyThread.find(params[:id])
    if @my_thread.update(my_thread_params)
      redirect_to my_threads_path
    else
      render 'edit'
    end
  end

  def destroy
    @my_thread = MyThread.find(params[:id])
    @my_thread.destroy
    redirect_to my_threads_path
  end

  private

  def login_check
    if session[:user_id].nil?
      flash[:alert] = 'ログインしてください'
      redirect_to '/'
    end
  end

  def my_thread_params
    params.require(:my_thread).permit(:title, :text, :user_id)
  end
end

app/helpers/my_threads/comments_helper.rb
# frozen_string_literal: true

module MyThreads::CommentsHelper
end

app/helpers/my_threads_helper.rb
# frozen_string_literal: true

module MyThreadsHelper
end

app/views/my_threads/_form.html.erb
<%= form_for @my_thread do |f| %>
  <p>
	<%= f.text_field :title, placeholder:'enter title' %>
  </p>

  <p>
	<%= f.text_area :text, placeholder:'enter text' %>
  </p>

  <p>
	<%= f.submit %>
  </p>

  <% @my_thread.errors.full_messages.each do |message| %>
      <li> <%= message %></li>
  <% end %>


<% end %>

app/views/my_threads/edit.html.erb
<h2>スレッドを編集</h2>
<%= render 'form' %>

app/views/my_threads/index.html.erb
<h2>スレッド</h2>
<span>自分のID: <%= @myid %></span>

<!--
<p><%= link_to 'ユーザー情報編集', edit_user_registration_path %></p>
-->

<p><%= link_to 'ログアウト', destroy_user_session_path, :method => :delete %></p>

<%= link_to 'スレッドを追加',new_my_thread_path, class:'header-menu'%>

<ul>
	<% @my_threads.each do |my_thread| %>
	<li>
	<%= link_to my_thread.title, my_thread_comments_path(my_thread)%>
	
	<span>投稿者ID: <%= my_thread.user_id %></span>

	<% if my_thread.user_id == @myid %>
		<%= link_to '[編集]',edit_my_thread_path(my_thread), class:'command' %>
	
		<%= link_to '[削除]',
		my_thread_path(my_thread), 
		method: :delete,
		class:'command',
		data:{confirm: 'Sure?'}
		%>
	<% end %>

	</li>
	<% end %>
</ul>

app/views/my_threads/new.html.erb
<h2>スレッドを追加</h2>
<%= render 'form' %>

app/views/my_threads/show.html.erb
<h1>スレッド詳細</h1>
<p><%= simple_format @my_thread.text %></p>

<%= link_to 'コメント作成',new_my_thread_path, class:'header-menu'%>

<% if @my_thread.comments.any? %>
	<ul>
		<% @comments.each do |comment| %>
		<li>
			<%= comment.text %>
			
			<%= link_to '[x]',
			my_thread_comment_path(@my_thread, @comment), 
			method: :delete,
			class:'command',
			data:{confirm: 'Sure?'}
			%>

		</li>
		<% end %>	
	</ul>
<% end %>