config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'photos', to: 'photos#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    # authenticated :user do
    #  root :to => 'my_threads#index', as: :authenticated_root
    # end
    # unauthenticated :user do
    root to: 'users/sessions#new', as: :unauthenticated_root
    # end
    # post '/users/sign_up', to: 'users/registrations#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_threads do
    resources :comments
  end
end

# devise_for :users, :controllers => {
#:registrations => 'users/registrations',
#:sessions => 'users/sessions',
#:passwords => "users/passwords"
# }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if user_signed_in? %>
    <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
  <% end %>

    <div class = "container">
    <h1><%= link_to image_tag('board.png', class: 'logo'), my_threads_path %></h1>

    <%= yield %>
    </div>
  </body>
</html>